dateModified: 1595580665
email:
  fromEmail: bjornar@noenreklame.no
  fromName: admin
  replyToEmail: null
  template: ''
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  1e90d02a-c0c4-4567-b346-020449aecd79:
    name: Error
  30709f5d-3519-472d-8340-b48451e87427:
    name: Common
  7970585d-b0d3-473e-b88a-e8a4e1d90dc3:
    name: Images
fields:
  5aa84d0b-6386-43ee-bdbd-73d9346412c7:
    contentColumnType: text
    fieldGroup: 1e90d02a-c0c4-4567-b346-020449aecd79
    handle: errorHeadline
    instructions: ''
    name: 'Error Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  80573c97-7621-48c7-8d94-3dddfccdca00:
    contentColumnType: text
    fieldGroup: 7970585d-b0d3-473e-b88a-e8a4e1d90dc3
    handle: optimizedImages
    instructions: ''
    name: 'Optimized Images'
    searchable: false
    settings:
      displayDominantColorPalette: '1'
      displayLazyLoadPlaceholderImages: '1'
      displayOptimizedImageVariants: '1'
      variants:
        -
          __assoc__:
            -
              - width
              - '1200'
            -
              - useAspectRatio
              - '1'
            -
              - aspectRatioX
              - '16'
            -
              - aspectRatioY
              - '9'
            -
              - retinaSizes
              -
                - '1'
            -
              - quality
              - '82'
            -
              - format
              - jpg
        -
          __assoc__:
            -
              - width
              - '992'
            -
              - useAspectRatio
              - '1'
            -
              - aspectRatioX
              - '16'
            -
              - aspectRatioY
              - '9'
            -
              - retinaSizes
              -
                - '1'
            -
              - quality
              - '82'
            -
              - format
              - jpg
        -
          __assoc__:
            -
              - width
              - '768'
            -
              - useAspectRatio
              - '1'
            -
              - aspectRatioX
              - '4'
            -
              - aspectRatioY
              - '3'
            -
              - retinaSizes
              -
                - '1'
            -
              - quality
              - '60'
            -
              - format
              - jpg
        -
          __assoc__:
            -
              - width
              - '576'
            -
              - useAspectRatio
              - '1'
            -
              - aspectRatioX
              - '4'
            -
              - aspectRatioY
              - '3'
            -
              - retinaSizes
              -
                - '1'
            -
              - quality
              - '60'
            -
              - format
              - jpg
    translationKeyFormat: null
    translationMethod: none
    type: nystudio107\imageoptimize\fields\OptimizedImages
  936d5c3d-d2fc-41cf-abdb-cc47c121f192:
    contentColumnType: string
    fieldGroup: 1e90d02a-c0c4-4567-b346-020449aecd79
    handle: errorImage
    instructions: ''
    name: 'Error Image'
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:408f99a3-3b3a-4e7b-9779-088ca5dd6b96'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:408f99a3-3b3a-4e7b-9779-088ca5dd6b96'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:408f99a3-3b3a-4e7b-9779-088ca5dd6b96'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ce37128e-04a8-4b48-aa20-4cbe4eeca9cf:
    contentColumnType: text
    fieldGroup: 1e90d02a-c0c4-4567-b346-020449aecd79
    handle: errorText
    instructions: ''
    name: 'Error Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
graphql:
  schemas:
    6bbd47c7-b787-4070-b2e6-5c5a160a0ba1:
      isPublic: true
      name: 'Public Schema'
    7f928e11-73a1-4704-8a52-1a81becf861e:
      isPublic: true
      name: 'Public Schema'
plugins:
  async-queue:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  fastcgi-cache-bust:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: false
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      createColorPalette: true
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - $SERVERLESS_SHARP_CLOUDFRONT_URL
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
                -
                  - includeBucketPrefix
                  - ''
      lowerQualityRetinaImageVariants: false
      transformClass: nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  webperf:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
sections:
  5b25bdbf-d19f-4ecd-bae7-db11b349d944:
    enableVersioning: false
    entryTypes:
      3cef9d16-36bc-4fd9-855e-3d2dbdb3c3c6:
        handle: errors
        hasTitleField: true
        name: Errors
        sortOrder: 1
        titleFormat: null
        titleLabel: Title
    handle: errors
    name: Errors
    propagationMethod: all
    siteSettings:
      fbb717e7-43b9-470b-9e3c-8a85eee0ccd0:
        enabledByDefault: true
        hasUrls: false
        template: null
        uriFormat: ''
    type: channel
  d01dd714-f689-45e1-a9ab-7ef5dfed7f97:
    enableVersioning: false
    entryTypes:
      92e0121a-41bf-462d-ba1c-4e8becc82038:
        handle: homepage
        hasTitleField: false
        name: Homepage
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: null
    handle: homepage
    name: Homepage
    propagationMethod: all
    siteSettings:
      fbb717e7-43b9-470b-9e3c-8a85eee0ccd0:
        enabledByDefault: true
        hasUrls: true
        template: index
        uriFormat: __home__
    type: single
siteGroups:
  54a200df-d659-4f63-938b-7155675f8629:
    name: Default
sites:
  fbb717e7-43b9-470b-9e3c-8a85eee0ccd0:
    baseUrl: $SITE_URL
    handle: default
    hasUrls: true
    language: en-GB
    name: Default
    primary: true
    siteGroup: 54a200df-d659-4f63-938b-7155675f8629
    sortOrder: 1
system:
  edition: pro
  live: true
  name: Craft
  schemaVersion: 3.4.11
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
volumes:
  408f99a3-3b3a-4e7b-9779-088ca5dd6b96:
    handle: site
    hasUrls: true
    name: Site
    settings:
      path: '@webroot/assets/site'
    sortOrder: 1
    type: craft\volumes\Local
    url: '@assetsUrl/assets/site'
